name: Build (macOS)

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1

    - name: Install dependencies
      run: flutter pub get

    - name: Generate Localizacion
      run: flutter gen-l10n

    - name: Build and test for macOS
      run: flutter build macos --debug
      if: runner.os == 'macOS'