name: Build (Windows)

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1

    - name: Install dependencies
      run: flutter pub get

    - name: Build and test for Windows (x64)
      run: flutter build windows --debug --target-platform=x64
      if: runner.os == 'Windows'

    - name: Build and test for Windows (x86)
      run: flutter build windows --debug --target-platform=x86
      if: runner.os == 'Windows'