name: Build (Linux)

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1

    - name: Install dependencies
      run: flutter pub get

    - name: Build and test for Linux (x86)
      run: flutter build linux --debug --target-platform=linux-x86
      if: runner.os == 'Linux'

    - name: Build and test for Linux (x64)
      run: flutter build linux --debug --target-platform=linux-x64
      if: runner.os == 'Linux'