name: Build (Linux)

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1

    - name: Install dependencies
      run: flutter pub get
    
    - name: Install Ninja and other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake pkg-config libgtk-3-dev libcairo2-dev libgl1-mesa-dev libgles2-mesa-dev ninja-build -y

    - name: Set CMAKE_MAKE_PROGRAM
      run: export CMAKE_MAKE_PROGRAM=/usr/bin/ninja
      if: runner.os == 'Linux'

    - name: Build and test for Linux
      run: flutter build linux --debug
      if: runner.os == 'Linux'